version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependabot
      - actions
    schedule:
      interval: monthly
    groups:
      all:
        patterns:
        - '*'      

  - package-ecosystem: npm
    directory: /
    labels:
      - dependabot
      - npm
    schedule:
      interval: monthly
    groups:
      types:
        patterns:
        - '@types/*'      
